#!/bin/sh
#
# @name PRAO
#
# @type Boat
# @class Boat
#
# @maintainer Guillaume Rozand <guillaume.rozand@epfl.ch>
#
# @output MAIN1 throttle
# @output MAIN2 rudder
# @output MAIN3 main foil
# @output MAIN4 small foil
#
# @output AUX adefinir
#

sh /etc/init.d/rc.boat_defaults

if [$AUTOCNF = yes]
then
        param set PWM_DISARMED 0
        param set PWM_MIN 1000
        param set PWM_MAX 2000
fi

# Configure this as fixed wing
set MAV_TYPE 11

# Set mixer
set MIXER prao

