#!/bin/sh
#
# @name PRAO
#
# @type Boat
#
# @maintainer Guillaume Rozand <guillaume.rozand@epfl.ch>
#
# @output MAIN1 rudder
# @output MAIN2 main foil
# @output MAIN3 small foil
# @output MAIN4 throttle
#
# @output AUX adefinir
#

sh /etc/init.d/rc.boat_defaults

if [$AUTOCNF = yes]
then
        param set PRAO_P_P 1
        param set PRAO_P_I 1
        param set PRAO_R_P 1
        param set PRAO_R_I 1
        param set PWM_DISARMED 0
        param set PWM_MIN 1000
        param set PWM_MAX 2000
fi

# Configure this as fixed wing
set MAV_TYPE 11

//Set mixer
set MIXER prao

# PWM
set PWM_DISARMED p:PWM_DISARMED
set PWM_MIN p:PWM_MIN
set PWM_MAX p:PWM_MAX
